version: '3.0'

services:
  mysql:
    image: 'mysql:8.0.42'
    container_name: creatine-mysql
    environment:
      MYSQL_ROOT_PASSWORD: abc@13579
      MYSQL_DATABASE: creatine_db
      MYSQL_USER: root
      MYSQL_PASSWORD: abc@13579
      TZ: Asia/Ho_Chi_Minh
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
    driver: local