server:
  port: ${CONTAINER_PORT}
spring:
  application:
    name: Creatine
  profiles:
    active: ${ACTIVE_PROFILE:dev}
  servlet:
    multipart:
      enabled: true
      max-file-size: 25MB
      max-request-size: 100MB
  threads:
    virtual:
      enabled: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
  mail:
    protocol: smtp
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  jackson:
    property-naming-strategy: SNAKE_CASE
    default-property-inclusion: non_null
    serialization:
      indent-output: true
      close-closeable: true
      fail-on-empty-beans: false
      flush-after-write-value: true
      write-dates-as-timestamps: false
      write-date-keys-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false
      accept-single-value-as-array: true

###########
# Creatine
###########
creatine:
  jwt:
    issuer: creatine.io
    secret-key: 7bf16aaa1e4b3da1b3e2a29cc2a380eddf0e883385a7ba668763a255bb75f5ebaf1cf449874526d991451f88cca12068486125159205655458abc14fa17d5192
    expires-in: 86_400_000
    refresh-expires-in: 108_000_000