server:
  port: 8080
spring:
  application:
    name: Creatine
  profiles:
    active: default
  threads:
    virtual:
      enabled: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://creatine-mysql:3306/creatineDB?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
    username: ${DATASOURCE_USERNAME:root}
    password: ${DATASOURCE_PASSWORD:abc@13579}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop

###########
# Creatine
###########
creatine:
  jwt:
    secret-key: 7bf16aaa1e4b3da1b3e2a29cc2a380eddf0e883385a7ba668763a255bb75f5ebaf1cf449874526d991451f88cca12068486125159205655458abc14fa17d5192
    expires-in: 86_400_000
    refresh-expires-in: 108_000_000