server:
  port: 8080
spring:
  application:
    name: Creatine
  threads:
    virtual:
      enabled: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://creatine-mysql:3306/creatineDB?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
    username: ${DATASOURCE_USERNAME:root}
    password: ${DATASOURCE_PASSWORD:abc@13579}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update