### Container Port
CONTAINER_PORT: 8080
ACTIVE_PROFILE: dev

### Database
SPRING_DATASOURCE_URL: jdbc:mysql://${DATASOURCE_HOST}:${DATASOURCE_PORT}/${DATASOURCE_DATABASE}?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
DATASOURCE_HOST: creatine-mysql
DATASOURCE_PORT: 3306
DATASOURCE_USERNAME: root
DATASOURCE_PASSWORD: abc@13579
DATASOURCE_DATABASE: creatineDB

### Mail
MAIL_USERNAME: creatine.io@gmail.com
MAIL_PASSWORD: bla_bla